version: "3.7"

services:
    file_server:
        container_name: file_server
        build: .
        volumes:
            - .:/app
        env_file:
            - ./.env
        environment:
            - PORT=5000
            - HOSTNAME=file_server

    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
        - file_server